@startuml name CynlrPS-LLSeq_PPxCP_HandShake

participant platform_parent_process as PFM_PP
participant process_manamger as PM
participant IO_Server as IOS
participant IO_Client as IOC
participant App_child_process as APP_CP

PFM_PP -> PM : Initialise Process Manager
PM -> IOS : Initialise IO Server (NamedPipeServer) 
activate IOS #LightGrey 
Note right of IOS : Wait for Clients to Connect
PFM_PP -> PFM_PP : Load Json Config
PFM_PP -> PFM_PP : Parse Json Config
PM -> PFM_PP : Request list of apps to launch
PFM_PP -> PM : Return list of apps to launch

note over PFM_PP, APP_CP : For each app in the list, perform Handshake

note over APP_CP : Apps that are downstream \n should first handshake with PFM \n and then its upstream app

par This is essentially a wrapper around the HandShake() function for the sake of visual appeal
PM -> APP_CP : Spawn App Child Process

/' Mutex is used to ensure only one app performs HandShake at a time.'/

PM -> PM : Hold Mutex for HandShake()
== HandShake() Sequence Start ==
Note Over PFM_PP, APP_CP: Need to change this with TransactNamedPipe
APP_CP -> IOC : Initialise IO Client (NamedPipeClient)
deactivate IOS #LightGrey
IOC -> IOS : Connect IO Client to IO Server
activate IOS #LightGreen
note left of IOS : Higher Level Handshake Semantics : 2 Way HandShake
IOS -> PM : Notify Client Connected (bool)
PM -> PM : Generate/Get HandShake Token (unique identifier for platform)
PM -> IOS : Pass PFM HandShake Token 
IOS -> IOC : Pass PFM HandShake Token
IOC -> IOS : Return with client specific (Unique Identifier) HandShake Token
IOC -> APP_CP : Pass Consolidated HandShake Token
IOS -> PM : Pass Consolidated HandShake Token
par
    APP_CP -> APP_CP : Register Handshake Token
else
    PM -> PM : Register Handshake Token and App Child Process
end

/'Essentially now there are two bytes added to each message; 
One Handshake token to make PFM aware of the destination it is sending to 
and to make the destination app know the message is generated by the PFM 
and is intended for it. if the exchange token is invalid the app can 
discard the message with reading it, improving performance and security.
Checksum though not essential, is done to esure message integrity.
'/

PFM_PP -> APP_CP : Ping (Make This User Event Driven)
APP_CP -> PFM_PP : Pong (Respond to Ping)

/'Now allow rest of the apps to perform HandShake'/

PM -> PM : Release Mutex for HandShake() 

== HandShake() Sequence End ==
end

Note Over PFM_PP, APP_CP : Any Failure of Intial Handshake should reinitialise all apps in sequence. Any Reinitialisation of app due to any Failure after the initial handshake can be done individual and easily with the registered tokens.

PFM_PP -> APP_CP : if Downstream App, command to setupIO with upstream app 
APP_CP -> APP_CP : SetupIO() with Upstream App

@enduml